IF
Global("BHBG1Quest2spawn","BG3700",0) 
Global("BHBG1Quest","GLOBAL",2)

THEN RESPONSE #100

CreateCreature("WIHOBG01",[2312.1346],N)
CreateCreature("WIHOBG01",[2350.1465],W)
CreateCreature("WIHOBG02",[2606.1249],S) 
CreateCreature("WIHOBG02",[2593.1442],N)
CreateCreature("WIHOBG03",[2272.1333],E)
CreateCreature("WIHOBG03",[2278.1471],N)
CreateCreature("WIHOBG04",[2674.1382],N)

SetGlobal("BHBG1Quest2spawn","BG3700",1)
END